theme: jekyll-theme-minimal
title: Srinath Devops Daily 
description: Posting Daily my project updates!

permissions:
  contents: read
  pages: write
  id-token: write

with:
  path: _posts    # <<<<< CHANGE to your folder name